# Generated by Django 5.1.6 on 2025-03-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="college",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="skills",
            field=models.TextField(help_text="Comma-separated list of skills"),
        ),
    ]
