# Generated by Django 5.1.6 on 2025-03-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_teammember_user_delete_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "skills",
                    models.TextField(help_text="Comma-separated list of skills"),
                ),
                ("role", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=255)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.team",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TeamMember",
        ),
    ]
