# Generated by Django 5.1.6 on 2025-03-15 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_teammember_college_alter_teammember_resume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_size",
            field=models.IntegerField(default=1),
        ),
    ]
