# Generated by Django 5.1.6 on 2025-03-20 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_teammembers_delete_teammember"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="student",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="interview_scheduled",
        ),
        migrations.RemoveField(
            model_name="projectapplication",
            name="interview_time",
        ),
        migrations.AddField(
            model_name="interview",
            name="scheduled_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interview",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.team",
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="applied_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.team"
            ),
        ),
    ]
