# Generated by Django 5.1.6 on 2025-03-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_team_leader_team_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="leader",
        ),
        migrations.RemoveField(
            model_name="team",
            name="name",
        ),
        migrations.RemoveField(
            model_name="team",
            name="project",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="user",
        ),
        migrations.AlterField(
            model_name="team",
            name="team_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="team_size",
            field=models.PositiveIntegerField(
                help_text="Number of members in the team"
            ),
        ),
    ]
