# Generated by Django 5.1.6 on 2025-03-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_interview_team_interview_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="member",
        ),
        migrations.AddField(
            model_name="interview",
            name="feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="status",
            field=models.CharField(default="Pending", max_length=100),
        ),
        migrations.AddField(
            model_name="interview",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.team",
            ),
            preserve_default=False,
        ),
    ]
