# Generated by Django 5.1.6 on 2025-03-20 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_remove_interview_member_interview_feedback_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.team",
            ),
        ),
    ]
