# Generated by Django 5.1.6 on 2025-03-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_remove_interview_feedback_remove_interview_status_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeamMembers",
            new_name="TeamMember",
        ),
    ]
